### ISSUE TITLE
check the header for keywords that tell whether we are under gyro mode

### ISSUE THREAD

**Issue by mgennaro** [spacetelescope/wfc3_dash#5]

**Comment by mgennaro** [comment]
Maybe not in the header but rather in the DADS database

**Comment by catherine-martlin** [comment]
See #21

**Comment by mgennaro** [comment]
#21 solves part of this issu: we now test that the inut file is an actual WFC3/IR IMA file. I have fed flts, raws and uvis data to the class and it correctly raises an exception. Still we do not test whether the expsoure was taken under gyro control, i.e. during an actual DASH observation. I do not think this should be a problem anymore, though. In principle the procedure we are creating should also be able to work on a "normal" stare mode observation, with the only effect of "producing a drizzled image of the individual reads, which should be "almost" identical to the drizzle product of the pipeline. We should verify that.
