### ISSUE TITLE
Choices on alignment method/catalogue

### ISSUE THREAD

**Issue by catherine-martlin** [spacetelescope/wfc3_dash#7]
Make it a choice for how to align/define your catalogue (have a default but provide other options).

**Comment by catherine-martlin** [comment]
We had a discussion about whether we wanted to include catalogue - catalogue; IMA image - catalogue; or single IMA read to the rest. We were considering focusing on having the last be the main method of our function, but that we will allow users to provide a catalogue. We are still discussing the creation and usage of a segmentation map, though.

**Comment by catherine-martlin** [comment]
Although, we are thinking of having people either provide a segmentation file or creating one (because star people wouldn't necessarily use or create those). Our program could create one that just takes the sources and then builds a seg file around the sources to help us ensure our drifted sources don't accidentally get flagged as CRs.

**Comment by obrienr2434** [comment]
Align method is now customizable. User can choose to align to a catalog of their choosing or a single IMA read to the rest. Catalog alignment is still iffy though (parameters need to be messed with a lot to be right)
